name: five-or-more
adopt-info: five-or-more
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  five-or-more:
    interface: dbus
    bus: session
    name: org.gnome.five-or-more

apps:
  five-or-more:
    command: usr/bin/five-or-more
    extensions: [ gnome-3-38 ]
    desktop: usr/share/applications/org.gnome.five-or-more.desktop

parts:
  five-or-more:
    source: https://gitlab.gnome.org/GNOME/five-or-more.git
    source-type: git
    source-tag: '3.32.3'
    source-depth: 1
# ext:updatesnap
#   version-format:
#     lower-than: '3.33'
#     no-9x-revisions: true
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=0)
    override-build: |
      sed -i.bak -e 's|Icon=org.gnome.five-or-more$|Icon=${SNAP}/meta/gui/org.gnome.five-or-more.png|g' $SNAPCRAFT_PART_SRC/data/org.gnome.five-or-more.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/256x256/org.gnome.five-or-more.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/five-or-more/current/usr/share/applications/org.gnome.five-or-more.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/usr]
    parse-info: [usr/share/metainfo/org.gnome.SwellFoop.appdata.xml]
    organize:
      snap/five-or-more/current/usr: usr
